/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdad5",
        "tertiary": "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#930007",
        "surface-container-lowest": "#0e0e0e",
        "error": "#ffb4ab",
        "status-info": "#3B82F6",
        "surface-card": "#0F0F0F",
        "secondary-fixed": "#ffdad6",
        "surface-bright": "#3a3939",
        "bg-canvas": "#050505",
        "inverse-on-surface": "#313030",
        "status-danger": "#EF4444",
        "border-subtle": "#202020",
        "on-secondary": "#690005",
        "on-tertiary-container": "#fff7f6",
        "border-control": "#2A2A2A",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#e9bcb6",
        "outline-variant": "#5e3f3b",
        "surface-secondary": "#111111",
        "border-standard": "#252525",
        "on-primary-fixed": "#410001",
        "primary-container": "#e50914",
        "primary": "#ffb4aa",
        "on-error": "#690005",
        "border-card": "#232323",
        "surface-interactive": "#151515",
        "tertiary-fixed": "#ffdad6",
        "surface-variant": "#353534",
        "secondary-container": "#a4020e",
        "surface-dim": "#131313",
        "on-secondary-container": "#ffaea5",
        "outline": "#af8782",
        "tertiary-container": "#e40d1a",
        "status-success": "#22C55E",
        "background": "#131313",
        "text-muted": "#737373",
        "on-background": "#e5e2e1",
        "error-container": "#93000a",
        "text-secondary": "#A3A3A3",
        "on-secondary-fixed-variant": "#93000a",
        "surface-container-highest": "#353534",
        "on-secondary-fixed": "#410002",
        "inverse-primary": "#c0000c",
        "tertiary-fixed-dim": "#ffb4ab",
        "surface-container-high": "#2a2a2a",
        "accent-ambient-subtle": "#3A0508",
        "on-tertiary": "#690005",
        "surface-tint": "#ffb4aa",
        "status-warning": "#F59E0B",
        "secondary": "#ffb4ab",
        "secondary-fixed-dim": "#ffb4ab",
        "accent-ambient-dark": "#240406",
        "on-primary": "#690003",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#93000a",
        "on-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "primary-fixed-dim": "#ffb4aa",
        "border-soft": "#1B1B1B",
        "text-contrast": "#FFFFFF",
        "on-primary-container": "#fff7f6",
        "surface-elevated": "#171717",
        "on-tertiary-fixed": "#410002",
        "text-primary": "#F5F5F5",
        "surface-hover": "#161616"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        "gutter-sm": "1rem",
        "margin-tablet": "2rem",
        "space-lg": "1.5rem",
        "gutter-lg": "2rem",
        margin: "2.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "display-mobile": ["Geist", "sans-serif"],
        "title-md": ["Geist", "sans-serif"],
        "title-sm": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"]
      }
    }
  },
  plugins: [],
}
